name: CI-1

on:
  pull_request:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: one
      - uses: actions/checkout@v3
        repository: c-mauderer/github-ci-2
        with:
          path: two
      - name: Generate some file
        run: |
          pwd
          ls -R
          echo "Hello from 1" > log
          git -C one log | head -20 >> log
          pwd
          ls -R
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: log-artifact
          path: log
      - uses: ./two/.github/actions/work
        with:
          arch: xxx
          sources-two: two
