name: CI-1

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v3
        id: cache
        with:
          path: log
          key: ${{ runner.os }}-xxx
      - uses: actions/checkout@v3
      - name: Generate some file
        run: |
          pwd
          ls -R
          echo "Hello from 1" > log
          git log | head -20 >> log
          pwd
          ls -R
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: log-artifact
          path: log
  call_second:
    needs: build
    steps:
      - uses: c-mauderer/github-ci-2/.github/workflows/work.yml@main
        with:
          arch: xxx
