name: CI-1

on:
  # Only manually for the moment
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate some file
        run: |
          pwd
          ls
          echo "Hello from 1" > log
          git log | head -20 >> log
          pwd
          ls
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: my-log
          path: log
  call_second:
    needs: build
    uses: c-mauderer/github-ci-2/.github/workflows/two.yml@main
    with:
      use_artifact: True
